adding possibility to assign build version & makin g sure the error log is working.

diff --git a/.github/workflows/tims_ultimate_workflow.yml b/.github/workflows/tims_ultimate_workflow.yml
--- a/.github/workflows/tims_ultimate_workflow.yml
+++ b/.github/workflows/tims_ultimate_workflow.yml
@@ -10,28 +10,19 @@ on:
         default: "false"
         type: boolean
 
-jobs:
-
-  error_log:
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4
-
-      # Failing step if show_message is 'false'
-      - name: Failing step if show_message is 'false'
-        run: |
-          echo "Error has occurd" > error.log
-          exit 1
-        if: ${{ github.event.inputs.show_message == 'false' }}
+  workflow_dispatch:
+    inputs: 
+      show_message:
+        description: "Write build version"
+        required: true
+        default: "false"
+        type: boolean
+      build_version:
+        description: "Enter the build version (e.g., v1.0.0)"
+        required: true
+        default: "v1.0.0"
         
-      # Upload error log if there is failure
-      - name: Upload error log
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with: 
-          name: error-log
-          path: error.log
+jobs:
 
   unittest:
 
@@ -57,7 +48,25 @@ jobs:
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    
+  
+  error_log:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Failing step if show_message is 'false'
+        run: |
+          echo "Error has occurd" > error.log
+          exit 1
+        if: ${{ github.event.inputs.show_message == 'true' }}
+        
+      - name: Upload error log
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with: 
+          name: error-log
+          path: error.log
 
   build:
 
@@ -66,7 +75,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -81,7 +90,7 @@ jobs:
         run: docker tag projectbounce ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:latest
 
       - name: Tag Docker image version
-        run: docker tag projectbounce ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:1.1
+        run: docker tag projectbounce ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:${{ github.event.inputs.build_version }}
 
       - name: Push Docker image to Docker Hub
         run: docker push ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:latest
